/*
 * Generated by dtrace(1M).
 */

#ifndef	_BUD_PROVIDER_H
#define	_BUD_PROVIDER_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#define BUD_STABILITY "___dtrace_stability$bud$v1$5_5_4_1_1_0_1_1_0_1_1_4_5_5_4"

#define BUD_TYPEDEFS "___dtrace_typedefs$bud$v2$6275645f6474726163655f636f6e6e656374696f6e5f74"

#if !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED

#define	BUD_FRONT_ACCEPT(arg0) \
do { \
	__asm__ volatile(".reference " BUD_TYPEDEFS); \
	__dtrace_probe$bud$front__accept$v1$6275645f6474726163655f636f6e6e656374696f6e5f74202a(arg0); \
	__asm__ volatile(".reference " BUD_STABILITY); \
} while (0)
#define	BUD_FRONT_ACCEPT_ENABLED() \
	({ int _r = __dtrace_isenabled$bud$front__accept$v1(); \
		__asm__ volatile(""); \
		_r; })


extern void __dtrace_probe$bud$front__accept$v1$6275645f6474726163655f636f6e6e656374696f6e5f74202a(const bud_dtrace_connection_t *);
extern int __dtrace_isenabled$bud$front__accept$v1(void);

#else

#define	BUD_FRONT_ACCEPT(arg0) \
do { \
	} while (0)
#define	BUD_FRONT_ACCEPT_ENABLED() (0)

#endif /* !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED */


#ifdef	__cplusplus
}
#endif

#endif	/* _BUD_PROVIDER_H */
